function r = th_titlepanel(action, varargin)

persistent mainFig lblModel lblType lblVarnum lblPnum viewParamsHndl viewVarsHndl model panel myPos fromTop lblHndl

if strcmp(action, 'init')
    %create the title
    mainFig = varargin{1};
    maincol = get(mainFig, 'color');
    myPos = varargin{2};
    tstr = varargin{3};
    pheight = myPos(4);
    

    %measure height from to of figure
    %so we can keep this constant if figure increases in height
    figheight= get(mainFig, 'position');
    figheight = figheight(4);
    fromTop = figheight-(myPos(2)+myPos(4));
    
    panel = uipanel('BorderType', 'etchedin', ...
        'Units','centimeters', ...
        'Position',myPos, ...
        'HandleVisibility', 'on', ...
        'BackgroundColor', maincol, ...
        'Parent', varargin{1}, ...
        'title', 'Model');

    lblPos(1) = 0.2;
    lblPos(2) = pheight-0.6;
    lblPos(3) = 1.1;
    lblPos(4) = 0.5;

    pheight = pheight/2 - 0.35;
    lblModel = uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[0.5 pheight 5 0.5], ...
                            'string','Model', ...
                            'BackgroundColor', maincol, ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontWeight', 'bold', ...
                            'FontSize', 12);
     uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[5.5 pheight 1.25 0.5], ...
                            'string','Type:', ...
                            'BackgroundColor', maincol, ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontSize', 12); 
     lblType = uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[7 pheight 3 0.5], ...
                            'string','-', ...
                            'BackgroundColor', maincol, ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontWeight', 'bold', ...
                            'FontSize', 12); 
    uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[11 pheight 2.5 0.5], ...
                            'string','Parameters:', ...
                            'BackgroundColor', maincol, ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontSize', 12); 
    lblPnum = uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[13.5 pheight 1.25 0.5], ...
                            'string','-', ...
                            'BackgroundColor', maincol, ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontWeight', 'bold', ...
                            'FontSize', 12); 
                        
    viewParamsHndl = uicontrol(...
                            'Style','pushbutton', ...
                            'Parent',panel , ...
                            'Units','centimeters', ...
                            'Position',[15.25 pheight-0.05 1.5 0.6], ...
                            'Interruptible','on', ...
                            'string', 'View', ...
                            'HandleVisibility', 'on', ...
                            'visible', 'off', ...
                            'FontUnits', 'points', 'FontSize', 10, ...
                             'tooltipstring', 'View a description of the model parameters', ...
                            'Callback','th_titlepanel(''viewParams'');');
                        
    uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[17.5 pheight 2.5 0.5], ...
                            'string','Variables:', ...
                            'BackgroundColor', maincol, ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontSize', 12); 
    lblVarnum = uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'BackgroundColor', maincol, ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[20 pheight 1 0.5], ...
                            'string','-', ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontWeight', 'bold', ...
                            'FontSize', 12); 
     viewVarsHndl = uicontrol(...
                            'Style','pushbutton', ...
                            'Parent',panel , ...
                            'Units','centimeters', ...
                            'Position',[21.5 pheight-0.05 1.5 0.6], ...
                            'Interruptible','on', ...
                            'string', 'View', ...
                            'HandleVisibility', 'on', ...
                            'visible', 'off', ...
                            'FontUnits', 'points', 'FontSize', 10, ...
                             'tooltipstring', 'View a description of the model variables', ...
                            'Callback','th_titlepanel(''viewVars'');');
    
%    lblHndl =  uicontrol('HorizontalAlignment', 'left','Parent',panel ,'Style', 'text','FontWeight', 'bold','Units','centimeters','position',lblPos,'string',tstr,'BackgroundColor', maincol, 'ForegroundColor', 'k', 'FontUnits', 'points', 'FontSize', 10);

    r = panel;
    
elseif strcmp(action, 'position')
    
    %called when figure resized. Ensures absolute position is maintained
    
    set(panel, 'visible', 'off');
    figheight= get(mainFig, 'position');
    figheight = figheight(4);
    pos = myPos;
    pos(2) = figheight-(fromTop+myPos(4));
    set(panel, 'position', pos);
    set(panel, 'visible', 'on');
    
elseif strcmp(action, 'newmodel')
    %model has beens set at startup, or when user changed model menu
    model = varargin{1};
    if ~isempty(model)
        set(lblModel, 'String', model.name);
        set(lblType, 'String', model.type);
        set(lblPnum, 'String', model.pnum);
        set(lblVarnum, 'String', model.vnum);
        set([viewParamsHndl viewVarsHndl], 'visible', 'on');
    else
        set(lblModel, 'String', 'No current model');
        set([lblType lblPnum lblVarnum] , 'String', '');
        set([viewParamsHndl viewVarsHndl], 'visible', 'off');
    end

 elseif strcmp(action,'viewParams')
    
    paramdescgui(model);
    
 elseif strcmp(action,'viewVars')
    
    vardescgui(model);
    
end