function forces = get_all_force_types()

%force definitions based on the content of get_force_expr()

forces = { ...
	'photo' ...
	'impulse' ...
	'hoffman' ...
	'sinewave' ...
	'60' ...
	'100' ...
	'200' ...
	'cts' ...
	'noforce' ...
};
