function r = sa_titlepanel(action, varargin)

global maincol

persistent lblModel lblType lblVarnum lblPnum viewParamsHndl viewVarsHndl

if strcmp(action, 'init')
    %create the title
    panel = uipanel('BorderType', 'etchedin', ...
        'Units','centimeters', ...
        'Position',varargin{2}, ...
        'HandleVisibility', 'on', ...
        'BackgroundColor', maincol, ...
        'title', 'Model', ...
        'Parent', varargin{1});
    pheight = varargin{2}(4);
    pheight = pheight/2 - 0.35;
    
    lblModel = uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[0.5 pheight 5 0.5], ...
                            'string','Model', ...
                            'BackgroundColor', maincol, ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontWeight', 'bold', ...
                            'FontSize', 12);
     uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[5.5 pheight 1.25 0.5], ...
                            'string','Type:', ...
                            'BackgroundColor', maincol, ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontSize', 12); 
     lblType = uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[7 pheight 3 0.5], ...
                            'string','-', ...
                            'BackgroundColor', maincol, ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontWeight', 'bold', ...
                            'FontSize', 12); 
    uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[11 pheight 2.5 0.5], ...
                            'string','Parameters:', ...
                            'BackgroundColor', maincol, ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontSize', 12); 
    lblPnum = uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[13.5 pheight 1.25 0.5], ...
                            'string','-', ...
                            'BackgroundColor', maincol, ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontWeight', 'bold', ...
                            'FontSize', 12); 
                        
    viewParamsHndl = uicontrol(...
                            'Style','pushbutton', ...
                            'Parent',panel , ...
                            'Units','centimeters', ...
                            'Position',[15.25 pheight-0.05 1.5 0.6], ...
                            'Interruptible','on', ...
                            'string', 'View', ...
                            'HandleVisibility', 'on', ...
                            'visible', 'off', ...
                            'FontUnits', 'points', 'FontSize', 10, ...
                            'Callback','sagui(''viewParams'');');
                        
    uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[17.5 pheight 2.5 0.5], ...
                            'string','Variables:', ...
                            'BackgroundColor', maincol, ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontSize', 12); 
    lblVarnum = uicontrol('FontUnits', 'normalized', 'Parent',panel , ...
                            'Style', 'text','Units','centimeters', ...
                            'HorizontalAlignment', 'left', ...
                            'position',[20 pheight 1 0.5], ...
                            'string','-', ...
                            'BackgroundColor', maincol, ...
                            'ForegroundColor', 'k', ...
                            'HandleVisibility', 'on', ...
                            'FontUnits', 'points', ...
                            'FontWeight', 'bold', ...
                            'FontSize', 12); 
     viewVarsHndl = uicontrol(...
                            'Style','pushbutton', ...
                            'Parent',panel , ...
                            'Units','centimeters', ...
                            'Position',[21.5 pheight-0.05 1.5 0.6], ...
                            'Interruptible','on', ...
                            'string', 'View', ...
                            'HandleVisibility', 'on', ...
                            'visible', 'off', ...
                            'FontUnits', 'points', 'FontSize', 10, ...
                            'Callback','sagui(''viewVars'');');
    
    r = panel;
    
elseif strcmp(action, 'newmodel')
    %model has beens set at startup, or when user changed model menu
    model = varargin{1};
    if ~isempty(model)
        set(lblModel, 'String', model.name);
        set(lblType, 'String', model.type);
        set(lblPnum, 'String', model.pnum);
        set(lblVarnum, 'String', model.vnum);
        set([viewParamsHndl viewVarsHndl], 'visible', 'on');
    else
        set(lblModel, 'String', 'No current model');
        set([lblType lblPnum lblVarnum] , 'String', '');
        set([viewParamsHndl viewVarsHndl], 'visible', 'off');
    end
    
end